tasks:
  - command: /opt/bin/entry_point.sh &
  - command: npm i && npm run compile -- -w & echo -e "\n\nYou are ready! \nRun your test by 'npm run test'\n"
image:
  file: .gitpod-config/.gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview
vscode:
  extensions:
    - LogiGear.gondola-studio-lite@2.0.11:V85S7fejpMHwtkVJlEr/aw==